# Generated by Django 3.0.6 on 2020-05-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
