# Generated by Django 3.0.6 on 2020-05-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
