# Generated by Django 2.2.3 on 2020-05-19 15:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200516_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_file',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
