# Generated by Django 2.2.3 on 2020-05-19 15:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_blog_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_file',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
