# Generated by Django 2.2.3 on 2020-05-19 17:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200519_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
