# Generated by Django 2.2.3 on 2020-05-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='claps',
            field=models.IntegerField(default=0),
        ),
    ]
