# Generated by Django 2.2.3 on 2020-05-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_claps'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Startup Story', 'Startup Story'), ('Random Reads', 'Random Reads'), ('Top N', 'Top N'), ('Tech Corner', 'Tech Corner'), ('Convid-19', 'Covid-19'), ('News', 'News'), ('Competetive Exams', 'Competetive Exams')], default='Random Reads', max_length=100),
        ),
    ]
