# Generated by Django 2.2.3 on 2020-05-27 10:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutAT', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
